import { FC } from 'react'
import Head from 'next/head'

import { HeadSeoProps } from './interface'

const HeadSeo: FC<HeadSeoProps> = ({
  title = 'Next App',
  content = 'Generated by create next app',
}) => {
  return (
    <Head>
      <title>{title}</title>
      <meta name="description" content={content} />
      <link rel="icon" href="/favicon.ico" />
      <link rel="preconnect" href="https://fonts.googleapis.com" />
      <link
        rel="preconnect"
        href="https://fonts.gstatic.com"
        crossOrigin="true"
      />
      <link
        href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400;500;600;700&family=Open+Sans:wght@300;400;500;600;700&display=swap"
        rel="stylesheet"
      />
    </Head>
  )
}

export default HeadSeo
